version: '3.8'

services:
  grpcserver:
    image: ghcr.io/spoc-puj/moving_average:5001-latest
    container_name: grpcserver
    ports:
      - "5001:5001"
    networks:
      - grpc_network
    stdin_open: true   # Habilitar entrada interactiva
    tty: true          # Asignar terminal al contenedor

  envoy:
    image: envoy-proxy
    container_name: envoy-proxy
    ports:
      - "8080:8080" # Exponer el puerto 8080 del contenedor en el puerto 8080 del host
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml # Montar el archivo de configuración de Envoy
    networks:
      - grpc_network
    depends_on:
      - grpcserver # Asegura que grpcserver esté listo antes de iniciar Envoy

networks:
  grpc_network:
    driver: bridge
